//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoTierraMedia.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BancoTierraMedia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap libro1 {
            get {
                object obj = ResourceManager.GetObject("libro1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Andúnië
        ///Annúminas
        ///Armenelos
        ///Arnor
        ///Avallónë
        ///Belegost
        ///Bree
        ///Eglarest
        ///Eldalondë
        ///Ephel Brandir
        ///Eriador
        ///Esgaroth
        ///Ethring
        ///Fangorn
        ///Forlond
        ///Formenos
        ///Fornost
        ///Framsburg
        ///Galabas
        ///Goblin Town
        ///Gondolin
        ///Gondor
        ///Harad
        ///Harlond
        ///Havens of Sirion
        ///Havens of the Falas
        ///Helm&apos;s Deep
        ///Hobbiton
        ///Hyarastorni
        ///Isengard
        ///Khazad-dûm
        ///Linhir
        ///Lothlorien
        ///Lothlórien
        ///Minas Morgul
        ///Minas Tirith
        ///Mirkwood
        ///Mithlond
        ///Moria
        ///Mordor
        ///Nindamos
        ///Nogrod
        ///Númenor
        ///Obel Halad
        ///Ondosto
        ///Osgiliath
        ///Pelargir
        ///Rivendell
        ///Rohan
        ///R [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string lugares_text {
            get {
                return ResourceManager.GetString("lugares_text", resourceCulture);
            }
        }
    }
}
